default_options: &default_options
  adapter:  postgresql
  encoding: utf8
  username:
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  timeout: 5000

development:
  <<: *default_options
  database: restaurant_booking

test:
  <<: *default_options
  database: test_restaurant_booking

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
